name: "artifacts"
on: workflow_dispatch
jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: node main.js
      - uses: actions/upload-artifact@v4
        with:
          name: random
          path: random.txt
          if-no-files-found: error
          retention-days: 7
  download-artifact:
    needs: generate-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: random
          # path: download
      - run: cat random.txt
