name: "variables and secrets"
on: workflow_dispatch
env:
  NAME: maria
jobs:
  setup-env-variables:
    runs-on: ubuntu-latest
    env:
      NAME: pepe
    steps:
      - run: echo "My name is $NAME"
      - run: echo "My name is $NAME"
        env:
          NAME: "marcos"
  read-global-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.NAME }}"
